model_path: ALINE/models/AL/inference/inference_model.pth
design_model_path: ALINE/models/AL/design/design_model.pth

config_name: train_prediction_design_al_benchmark

design_config_name: train_bed

save_path: results/al_benchmark
